local uci = require "uci"
local cjson = require "cjson"

local CONFIG = "gl-tor"
local TORRC = "/etc/tor/torrc"
local DSTNAT_INCLUDE = "/usr/share/nftables.d/chain-pre/dstnat/90-gl-tor.nft"
local FORWARD_INCLUDE = "/usr/share/nftables.d/chain-pre/forward/90-gl-tor.nft"

local function shell_quote(value)
	return "'" .. tostring(value or ""):gsub("'", "'\\''") .. "'"
end

local function write_file(path, content)
	local tmp = path .. ".tmp"
	local file = io.open(tmp, "w")
	if not file then
		return nil, "unable to write " .. path
	end
	file:write(content)
	file:close()
	if os.rename(tmp, path) then
		return true
	end
	os.remove(tmp)
	return nil, "unable to replace " .. path
end

local function read_file(path, limit)
	local file = io.open(path, "r")
	if not file then return "" end
	local data = file:read(limit or "*a") or ""
	file:close()
	return data
end

local function normalize_countries(values)
	local result, seen = {}, {}
	if type(values) ~= "table" then return result end
	for _, value in ipairs(values) do
		local code = tostring(value):upper()
		if code:match("^[A-Z][A-Z]$") and not seen[code] then
			seen[code] = true
			result[#result + 1] = code
		end
	end
	table.sort(result)
	return result
end

local function load_config()
	local cursor = uci.cursor()
	local enabled = cursor:get(CONFIG, "main", "enabled") == "1"
	local manual = cursor:get(CONFIG, "main", "manual") == "1"
	local countries = normalize_countries(cursor:get(CONFIG, "main", "country") or {})
	cursor:close()
	return enabled, manual, countries
end

local function save_config(enabled, manual, countries)
	local cursor = uci.cursor()
	if not cursor:get(CONFIG, "main") then
		cursor:set(CONFIG, "main", "settings")
	end
	cursor:set(CONFIG, "main", "enabled", enabled and "1" or "0")
	cursor:set(CONFIG, "main", "manual", manual and "1" or "0")
	cursor:delete(CONFIG, "main", "country")
	for _, country in ipairs(countries) do
		cursor:add_list(CONFIG, "main", "country", country)
	end
	cursor:commit(CONFIG)
	cursor:close()
end

local function render_torrc(manual, countries)
	local lines = {
		"# Generated by the GL.iNet Tor compatibility service.",
		"User tor",
		"DataDirectory /var/lib/tor",
		"PidFile /var/run/tor.pid",
		"RunAsDaemon 1",
		"SocksPort 127.0.0.1:9050",
		"TransPort 0.0.0.0:9040",
		"DNSPort 0.0.0.0:9053",
		"AutomapHostsOnResolve 1",
		"VirtualAddrNetworkIPv4 10.192.0.0/10",
		"Log notice syslog",
		"ClientUseIPv6 0",
	}
	if manual and #countries > 0 then
		local nodes = {}
		for _, country in ipairs(countries) do
			nodes[#nodes + 1] = "{" .. country .. "}"
		end
		lines[#lines + 1] = "ExitNodes " .. table.concat(nodes, ",")
		lines[#lines + 1] = "StrictNodes 1"
	end
	return table.concat(lines, "\n") .. "\n"
end

local function install_firewall_rules()
	local dstnat = table.concat({
		"# Generated by GL.iNet Tor compatibility service.",
		'meta nfproto ipv4 iifname "br-lan" udp dport 53 redirect to :9053',
		'meta nfproto ipv4 iifname "br-lan" tcp dport 53 redirect to :9053',
		'meta nfproto ipv4 iifname "br-lan" ip daddr != { 10.0.0.0/8, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.168.0.0/16, 224.0.0.0/4 } tcp flags & (fin | syn | rst | ack) == syn redirect to :9040',
	}, "\n") .. "\n"
	local forward = table.concat({
		"# Do not allow IPv6 to bypass the IPv4 Tor transparent proxy.",
		'meta nfproto ipv6 iifname "br-lan" reject comment "GL Tor IPv6 leak prevention"',
	}, "\n") .. "\n"
	local ok, err = write_file(DSTNAT_INCLUDE, dstnat)
	if not ok then return nil, err end
	return write_file(FORWARD_INCLUDE, forward)
end

local function remove_firewall_rules()
	os.remove(DSTNAT_INCLUDE)
	os.remove(FORWARD_INCLUDE)
end

local function apply(enabled, manual, countries)
	if enabled then
		local ok, err = write_file(TORRC, render_torrc(manual, countries))
		if not ok then return nil, err end
		ok, err = install_firewall_rules()
		if not ok then return nil, err end
		os.execute("/etc/init.d/firewall reload >/dev/null 2>&1")
		os.execute("/etc/init.d/tor enable >/dev/null 2>&1")
		local rc = os.execute("/etc/init.d/tor restart >/dev/null 2>&1")
		if rc ~= true and rc ~= 0 then
			return nil, "tor failed to start"
		end
	else
		os.execute("/etc/init.d/tor stop >/dev/null 2>&1")
		os.execute("/etc/init.d/tor disable >/dev/null 2>&1")
		remove_firewall_rules()
		os.execute("/etc/init.d/firewall reload >/dev/null 2>&1")
	end
	return true
end

local function process_running()
	local pipe = io.popen("pgrep -x tor 2>/dev/null")
	if not pipe then return false end
	local pid = pipe:read("*l")
	pipe:close()
	return pid ~= nil
end

local function bootstrap_log()
	local pipe = io.popen("logread 2>/dev/null | tail -n 300 | sed -n '/[Tt]or/p'")
	if not pipe then return "" end
	local data = pipe:read("*a") or ""
	pipe:close()
	if #data > 16384 then data = data:sub(-16384) end
	return data
end

return {
	get_config = function()
		local enabled, manual, countries = load_config()
		return {
			enable = enabled,
			manual = manual,
			countries = #countries > 0 and countries or cjson.empty_array,
		}
	end,

	set_config = function(args)
		args = args or {}
		local enabled = args.enable and true or false
		local manual = args.manual and true or false
		local countries = normalize_countries(args.countries)
		if manual and enabled and #countries == 0 then
			return { err_code = 1, err_msg = "Select at least one exit country." }
		end
		local ok, err = apply(enabled, manual, countries)
		if not ok then
			return { err_code = 2, err_msg = err }
		end
		save_config(enabled, manual, countries)
		return {}
	end,

	get_status = function()
		local enabled = load_config()
		local log = bootstrap_log()
		local bootstrapped = log:match("Bootstrapped 100%%") ~= nil
		return {
			status = enabled and process_running() and bootstrapped and 1
				or enabled and 2 or 0,
			log = log,
		}
	end,
}
