#!/bin/sh /etc/rc.common
# Before network/nginx, so gl-session is registered on ubus by the time
# nginx workers (and later, other RPC objects) start calling it.
START=10
STOP=10

USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/eco /usr/sbin/gl-ngx-session
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
